version: "3"

services:
  db:
    image: postgres:16.6-alpine
    container_name: db-postgres
    restart: always
    volumes:
      # for mac: 
      # _postgres_data:/var/lib/postgresql/data/
      - ./_postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.txt
    networks:
      - v-network
  web:
    image: boilerplate:0.0.1
    restart: always
    container_name: backends
    volumes:
      - ./sock/:/sock/
      - ./project/:/usr/src/app/
      - ./logs/:/logs/
      - ./static/:/static/
    command: sh entrypoint.sh
    env_file:
      - env.txt
    networks:
      - v-network
    environment:
      - PYTHONUNBUFFERED=1
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./react/dist:/var/www/frontend
      - ./static/:/var/www/static
      - ./project/media/:/var/www/media/
      - ./sock/:/sock/
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    networks:
      - v-network

networks:
  v-network:
    external: false

# NOTE: for mac declare follwing volumes
# volumes:
#  _postgres_data: