version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: template_postgres
    restart: always
    volumes:
      - _postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.txt
    networks:
      - v-network
  web:
    image: project/template:0.0.1
    restart: always
    container_name: template_web
    volumes:
      - ./sock/:/sock/
      - ./project/:/usr/src/app/
      - ./logs/:/logs/
      - ./static/:/static/
    command: sh entrypoint.sh
    env_file:
      - env.txt
    networks:
      - v-network
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    container_name: template_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./react/dist:/var/www/frontend
      - ./static/:/var/www/static
      - ./project/media/:/var/www/media/
      - ./sock/:/sock/
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    networks:
      - v-network

networks:
  v-network:
    external: false

# NOTE: remove this if you're not on mac with ARM chip
volumes:
  _postgres_data: